---
name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true
          # Added to ensure the linter has the context it needs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: [super-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t "$DOCKERHUB_USERNAME/my-image:${{ github.sha }}" .
      
      - name: Log in to Docker Hub
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t "$DOCKERHUB_USERNAME/kiii:latest" -t "$DOCKERHUB_USERNAME/kiii:${{ github.sha }}" .
          docker push "$DOCKERHUB_USERNAME/kiii" --all-tags